# Generated by Django 4.0.4 on 2022-12-20 10:23

import apps.models.abstract
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.models.abstract.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', apps.models.abstract.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(max_length=30, verbose_name='Название тега')),
                ('weight', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Вес тега')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
            },
        ),
    ]
