# Generated by Django 4.0.4 on 2022-12-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
