# Generated by Django 4.0.4 on 2022-12-14 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0002_alter_tag_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='modified',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='exportable',
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='weight',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Вес тега'),
        ),
    ]
