# Generated by Django 4.0.4 on 2022-12-21 15:49

import apps.models.abstract
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_update_indicator_activities_and_sessions'),
        ('tag', '0002_alter_tag_created_at_alter_tag_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorTagRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.models.abstract.CreationDateTimeField(auto_now_add=True, verbose_name='Дата и время создания связи')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Если значение пустое, значит связь существующая', null=True, verbose_name='Дата и время удаления связи')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.indicator')),
            ],
            options={
                'verbose_name': 'Связь индикатор-фид',
                'verbose_name_plural': 'Связи индикатор-фид',
                'db_table': 'indicator_tag_relationships',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='indicators',
            field=models.ManyToManyField(blank=True, null=True, through='tag.IndicatorTagRelationship', to='indicator.indicator'),
        ),
        migrations.AddField(
            model_name='indicatortagrelationship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag'),
        ),
    ]
