# Generated by Django 4.0.4 on 2022-12-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_alter_source_table_delete_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
