# Generated by Django 4.0.4 on 2022-12-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='tag.tag'),
        ),
    ]
