# Generated by Django 4.0.4 on 2022-12-21 11:33

import apps.models.abstract
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('indicator', '0002_alter_indicatoractivities_options_and_more'), ('indicator', '0003_alter_session_access_token')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatoractivities',
            options={'verbose_name': 'Таймлайн активности по индикатору', 'verbose_name_plural': 'Таймлайны активностей по индикаторам'},
        ),
        migrations.RemoveField(
            model_name='indicatoractivities',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='indicatoractivities',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicatoractivities',
            name='created_at',
            field=apps.models.abstract.CreationDateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='indicatoractivities',
            name='type',
            field=models.TextField(choices=[('add_comment', 'add-comment'), ('add_tag', 'add-tag'), ('remove_tag', 'remove-tag'), ('move_to_archive', 'move-to-archive'), ('move_from_archive', 'move-from-archive')], verbose_name='Тип'),
        ),
        migrations.AlterModelTable(
            name='indicatoractivities',
            table='indicator_activities',
        ),
        migrations.AlterField(
            model_name='session',
            name='access_token',
            field=models.TextField(max_length=255, verbose_name='Токен доступа MD5'),
        ),
    ]
