# Generated by Django 4.0.4 on 2022-12-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='type',
            field=models.CharField(default='IPAD', max_length=13, verbose_name='Тип индикатора'),
        ),
    ]
