# Generated by Django 4.0.4 on 2022-12-21 08:36

import apps.models.abstract
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('indicator', '0002_remove_indicator_ioc_context_affected_products_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='id',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='tag.tag'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='IndicatorActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.models.abstract.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', apps.models.abstract.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('type', models.CharField(choices=[('add_comment', 'add-comment'), ('add_tag', 'add-tag'), ('remove_tag', 'remove-tag'), ('move_to_archive', 'move-to-archive'), ('move_from_archive', 'move-from-archive')], max_length=50, verbose_name='Тип')),
                ('details', models.JSONField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='indicator.indicator', verbose_name='Активность по индикатору')),
            ],
            options={
                'verbose_name': 'Активность по Индикатору',
                'verbose_name_plural': 'Активности по Индикатору',
                'db_table': 'activities',
            },
        ),
    ]
