# Generated by Django 4.0.4 on 2022-12-21 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicator', '0003_remove_indicator_id_alter_indicator_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='indicator',
            table='indicators',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, verbose_name='Токен доступа MD5')),
                ('last_activity_at', models.DateTimeField(verbose_name='Дата и время последней активности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания сессии')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
                'db_table': 'sessions',
            },
        ),
    ]
