# Generated by Django 4.0.4 on 2022-12-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_alter_indicator_table_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='last_activity_at',
            field=models.DateTimeField(editable=False, verbose_name='Дата и время последней активности'),
        ),
    ]
