# Generated by Django 4.0.4 on 2022-12-21 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_alter_session_last_activity_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='uuid',
        ),
        migrations.AddField(
            model_name='indicator',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
