# Generated by Django 4.0.4 on 2022-12-21 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0006_remove_indicator_uuid_indicator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
