psvc:
  name: Консоль мониторинга и управления фидов
  description: Консоль мониторинга и управления
  publishAPI: true

replicaCount: 1

env:
  DEBUG: True
  SWAGGER: True
  FEEDS_IMPORTING_SERVICE_URL: http://feeds-importing-worker.isys-threat-intelligence-dev
  SCORE_SERVICE_URL: https://data-proccessing-worker.threat-intelligence.dev.rshbdev.ru

resources:
  limits:
    memory: 1Gi
    cpu: 1000m
  requests:
    memory: 512Mi
    cpu: 100m


databases:
  - type: POSTGRESQL
    host: 10.7.27.113
    port: 5432
    name: db

strategyType: Recreate

links:
  - targetProtocol: HTTP
    targetInformationSystemId: threat-intelligence
    targetServiceId: console-api
    endpointMapping:
    - endpointAlias: /api


  - targetProtocol: HTTP
    targetInformationSystemId: threat-intelligence
    targetServiceId: feeds-importing-worker

  - targetProtocol: HTTP
    targetInformationSystemId: threat-intelligence
    targetServiceId: data-processing-worker

