replicaCount: 1

resources:
  limits:
    memory: 1Gi
    cpu: 1
  requests:
    memory: 512Mi
    cpu: 100m

env:
  # app
  DEBUG: True
  SWAGGER: True

  # db
  POSTGRES_SERVER: 10.7.77.7
  POSTGRES_DB: mydb
  POSTGRES_PORT: 5432

psvc:
  name: Сервис представления событийнных данных
  description: Сервис для представления данных о событяих
  istioSidecarSettings:
    limits:
      memory: 200Mi
      cpu: 200m
    requests:
      memory: 50Mi
      cpu: 10m

vaultSecretKeys:
  - POSTGRES_PASSWORD
  - POSTGRES_USER

strategyType: Recreate

databases:
    type: POSTGRESQL
    host: 10.7.77.7
    port: 5432
    name: mydb

links:
  - targetProtocol: HTTP
    targetInformationSystemId: threat-intelligence
    targetServiceId: console-api
    endpointMapping:
  - endpointAlias: /api
