# Generated by Django 4.0.4 on 2022-12-16 15:27

import console_api.apps.models.abstract
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', console_api.apps.models.abstract.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', console_api.apps.models.abstract.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('type_of_feed', models.CharField(default='IPAD', max_length=13, verbose_name='Тип фида')),
                ('format_of_feed', models.CharField(default='TXT', max_length=15, verbose_name='Формат фида')),
                ('auth_type', models.CharField(default='NAU', max_length=7, verbose_name='Тип авторизации')),
                ('polling_frequency', models.CharField(choices=[('NEVER', 'NVR'), ('THIRTY_MINUTES', 'M30'), ('ONE_HOUR', 'HR1'), ('TWO_HOURS', 'HR2'), ('FOUR_HOURS', 'HR4'), ('EIGHT_HOURS', 'HR8'), ('SIXTEEN_HOURS', 'H16'), ('TWENTY_FOUR_HOURS', 'H24')], default='NVR', max_length=17, verbose_name='Частота обновления фида')),
                ('auth_login', models.CharField(blank=True, max_length=32, null=True, verbose_name='Логин для авторизации')),
                ('auth_password', models.CharField(blank=True, max_length=64, null=True, verbose_name='Пароль для авторизации')),
                ('auth_querystring', models.CharField(blank=True, max_length=128, null=True, verbose_name='Строка для авторизации')),
                ('separator', models.CharField(blank=True, max_length=8, null=True, verbose_name='Разделитель для CSV формата')),
                ('custom_field', models.CharField(blank=True, max_length=128, null=True, verbose_name='Кастомное поле')),
                ('sertificate', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл сертификат')),
                ('vendor', models.CharField(max_length=32, verbose_name='Вендор')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название фида')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на фид')),
                ('confidence', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Достоверность')),
                ('records_quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество записей')),
                ('update_status', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED'), ('UPDATE_ERROR', 'UPDATE_ERROR')], default='ENABLED', max_length=15)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фид',
                'verbose_name_plural': 'Фиды',
                'db_table': 'feeds',
            },
        ),
        migrations.CreateModel(
            name='ParsingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', console_api.apps.models.abstract.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', console_api.apps.models.abstract.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
            ],
            options={
                'verbose_name': 'Правило парсинга',
                'verbose_name_plural': 'Правила парсинга',
            },
        ),
    ]
