# Generated by Django 4.0.4 on 2022-12-21 10:23

import apps.models.abstract
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicator', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.models.abstract.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', apps.models.abstract.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.TextField(unique=True, verbose_name='Название Фида')),
                ('provider', models.TextField(verbose_name='Название поставщика Фида')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание Фида')),
                ('format', models.TextField(choices=[('json', 'json'), ('stix_1', 'stix-1'), ('stix_2', 'stix-2'), ('misp', 'misp'), ('csv', 'csv'), ('txt', 'txt'), ('xml', 'xml')], default='txt', verbose_name='Формат фида')),
                ('url', models.TextField(verbose_name='Ссылка на файл Фида')),
                ('auth_type', models.TextField(blank=True, help_text='Например: http-basic, api-token', null=True, verbose_name='Формат фида')),
                ('auth_api_token', models.TextField(verbose_name='API токен')),
                ('auth_login', models.TextField(verbose_name='Логин HTTP Basic Auth')),
                ('auth_pass', models.TextField(verbose_name='Пароль HTTP Basic Auth')),
                ('certificate', models.BinaryField(verbose_name='Сертификат')),
                ('use_taxii', models.BooleanField(blank=True, default=False, null=True)),
                ('polling_frequency', models.TextField(help_text='Формат CronTab', verbose_name='Частота обновления')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Вес фида')),
                ('available_fields', models.JSONField(verbose_name='Список доступных полей в индикаторах фида')),
                ('parsing_rules', models.JSONField(blank=True, null=True, verbose_name='Настройки парсинга')),
                ('status', models.TextField(choices=[('failed_to_update', 'failed-to-update'), ('is_loading', 'is-loading'), ('normal', 'normal')], verbose_name='Статус фида')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включен ли фид?')),
                ('is_truncating', models.BooleanField(default=False, verbose_name='Включено ли обрезание фида?')),
                ('max_records_count', models.DecimalField(decimal_places=5, max_digits=20)),
                ('indicators', models.ManyToManyField(blank=True, null=True, to='indicator.indicator')),
            ],
            options={
                'verbose_name': 'Фид',
                'verbose_name_plural': 'Фиды',
                'db_table': 'feeds',
            },
        ),
    ]
