# Generated by Django 4.0.4 on 2022-12-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0001_initial'),
        ('indicator', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='indicators',
            field=models.ManyToManyField(blank=True, related_name='feeds', to='indicator.indicator', verbose_name='Индикатор'),
        ),
        migrations.AddField(
            model_name='feed',
            name='parsing_rules',
            field=models.ManyToManyField(blank=True, related_name='feed_parsing_rules', to='feed.parsingrule', verbose_name='Правила для парсинга'),
        ),
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='source.source'),
        ),
    ]
