# Generated by Django 4.0.4 on 2022-12-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='auth_type',
            field=models.CharField(default='NAU', max_length=7, verbose_name='Тип авторизации'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='format_of_feed',
            field=models.CharField(default='TXT', max_length=15, verbose_name='Формат фида'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='type_of_feed',
            field=models.CharField(default='IPAD', max_length=13, verbose_name='Тип фида'),
        ),
    ]
