# Generated by Django 4.0.4 on 2022-12-21 10:47

import apps.models.abstract
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('feed', '0002_indicatorfeedrelationship_alter_feed_indicators_and_more'), ('feed', '0003_rename_feed_id_indicatorfeedrelationship_feed_and_more')]

    dependencies = [
        ('indicator', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorFeedRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', apps.models.abstract.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('created_at', apps.models.abstract.CreationDateTimeField(auto_now_add=True, verbose_name='Дата и время создания связи')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Если значение пустое, значит связь существующая', null=True, verbose_name='Дата и время удаления связи')),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.indicator')),
            ],
            options={
                'verbose_name': 'Связь индикатор-фид',
                'verbose_name_plural': 'Связи индикатор-фид',
                'db_table': 'indicator_feed_relationships',
            },
        ),
        migrations.RemoveField(
            model_name='feed',
            name='indicators',
        ),
        migrations.AddField(
            model_name='feed',
            name='indicators',
            field=models.ManyToManyField(blank=True, null=True, through='feed.IndicatorFeedRelationship', to='indicator.indicator'),
        ),
        migrations.AddField(
            model_name='indicatorfeedrelationship',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feed'),
        ),
        migrations.RenameField(
            model_name='indicatorfeedrelationship',
            old_name='indicator_id',
            new_name='indicator',
        ),
        migrations.RemoveField(
            model_name='indicatorfeedrelationship',
            name='updated_at',
        ),
    ]
