# Generated by Django 4.0.4 on 2022-12-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_sertificate_feed_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='source_url',
            field=models.CharField(default='asda', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='use_taxii',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
