# Generated by Django 4.0.4 on 2022-12-21 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='format',
            field=models.TextField(choices=[('json', 'json'), ('stix_1', 'stix-1'), ('stix_2', 'stix-2'), ('misp', 'misp'), ('csv', 'csv'), ('txt', 'txt'), ('xml', 'xml')], default='txt', verbose_name='Формат фида'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='max_records_count',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.TextField(verbose_name='Ссылка на файл Фида'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Вес фида'),
        ),
    ]
