# Generated by Django 4.0.4 on 2022-12-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_indicators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='available_fields',
        ),
    ]
