# Generated by Django 4.0.4 on 2022-12-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_feed_format_alter_feed_max_records_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включен ли фид?'),
        ),
    ]
