# Generated by Django 4.0.4 on 2022-12-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_feed_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='parsingrule',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='parsingrule',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
