# Generated by Django 4.0.4 on 2022-12-21 10:52

import apps.models.abstract
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event', models.JSONField(help_text='Информация о Событии (Объект из Kafka)', verbose_name='Информация о событии')),
                ('detection_event', models.JSONField(verbose_name='Информация о событии, которая отправляется во внешнюю ИС (SIEM)')),
                ('tags_weight', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Вес тегов')),
                ('created_at', apps.models.abstract.CreationDateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicator.indicator', verbose_name='Обнаруженный индикатор для данного события')),
            ],
            options={
                'verbose_name': 'Обнаружение',
                'verbose_name_plural': 'Обнаружения',
                'db_table': 'detections',
            },
        ),
    ]
