# Generated by Django 4.0.4 on 2022-12-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'verbose_name': 'Обнаружение', 'verbose_name_plural': 'Обнаружения'},
        ),
        migrations.AlterModelTable(
            name='detection',
            table='detections',
        ),
    ]
