# Generated by Django 4.0.4 on 2022-12-21 10:57

import apps.models.abstract
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionTagRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.models.abstract.CreationDateTimeField(auto_now_add=True, verbose_name='Дата и время создания связи')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.detection')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
            ],
            options={
                'verbose_name': 'Связь обнаружение-тег',
                'verbose_name_plural': 'Связи обнаружение-тег',
                'db_table': 'detection_tag_relationships',
            },
        ),
    ]
