# Generated by Django 4.0.4 on 2022-12-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_detectiontagrelationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detection',
            old_name='indicator_id',
            new_name='indicator',
        ),
    ]
