# Generated by Django 4.0.4 on 2022-12-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('detections', '0003_rename_indicator_id_detection_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, through='detections.DetectionTagRelationship', to='tag.tag'),
        ),
    ]
