# Generated by Django 4.0.4 on 2022-12-21 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.TextField(unique=True, verbose_name='Логин')),
                ('password', models.TextField(db_column='pass_hash', verbose_name='Хэшированный пароль')),
                ('full_name', models.TextField(verbose_name='Полное имя')),
                ('role', models.TextField(choices=[('analyst', 'analyst'), ('admin', 'admin'), ('auditor', 'auditor')], verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Есть ли у пользователя доступ к системе (не отключен ли он?)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания Пользователя')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления Пользователя')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время удаления Пользователя')),
                ('staff', models.BooleanField(default=False, verbose_name='Персонал?')),
                ('admin', models.BooleanField(default=False, verbose_name='Админ?')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ID Пользователя, кто создал этого Пользователя')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
